application: crxdoczh2
version: 0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
  expiration: 365d
- url: /.*
  script: handler.app
  secure: always

pagespeed:
  domains_to_rewrite:
  - developer.chrome.com
  enabled_rewriters:
  - CollapseWhitespace
  - RemoveComments
  - RemoveQuotes
  - MinifyCss
  - ImageAddDimensions

