application: <REPLACE_WITH_YOUR_SAMPLES_APP_ID>
version: 2-0-17
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/.*
  script: appengine_main.py
  login: admin
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: appengine_main.py

env_variables:
  CRXDOCZH_SLAVE_TYPE: 'samples'
  CRXDOCZH_GITHUB_API_USERNAME: '<REPLACE_WITH_YOUR_GITHUB_API_USERNAME>'
  CRXDOCZH_GITHUB_API_PASSWORD: "<REPLACE_WITH_YOUR_GITHUB_API_PASSWORD>"
