application: <REPLACE_WITH_YOUR_DOCS_APP_ID>
version: 2-0-17
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
- url: /(stable|beta|dev|trunk)/_/api/<REPLACE_WITH_YOUR_DOCS_API_KEY>/html/docs/(apps|extensions)/.*
  script: appengine_main.py
- url: /.*
  script: appengine_main.py
  login: admin

env_variables:
  CRXDOCZH_SLAVE_TYPE: 'docs'

